elasticsearch:
  host: "${ELASTICSEARCH_HOST:localhost:9200}"
  username: "${ELASTICSEARCH_USERNAME:elastic}"
  password: "${ELASTICSEARCH_PASSWORD:elastic}"
  ssl:
    enabled: "${ELASTICSEARCH_SSL_ENABLED:true}"
    trustAllCertificates: "${ELASTICSEARCH_SSL_TRUST_ALL:true}"
